### ISSUE TITLE
Change Modal Font Size 

### ISSUE THREAD

**Issue by AletaHakan** [AletaHakan/TAAD#34]
# Fix modal font size

I don’t like the size of the text here on the modal. 

Noticed on Upsilon —> Author Modal

![screen shot 2018-05-19 at 5 57 45 pm](https://user-images.githubusercontent.com/29622724/40274214-358c1f6e-5b8e-11e8-89e0-d356b108372d.png)

**Comment by deepanjali19** [comment]
Hello @AletaHakan ! I would like to work on this issue.

Thank you so much!
